version: '3.8'

services:

  proxy:
    image: nginx:1.24.0
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt:ro
      - ./nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key:ro
    depends_on:
      jatos:
        condition: service_healthy
    ports:
      - 80:80
      - 443:443

  jatos:
    image: jatos/jatos:latest
    restart: always
    ports:
      - 9000
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      # If you have a base path (if you set 'jatos.urlBasePath') you have to change the URL path here
      test: ["CMD", "curl", "-f", "http://localhost:9000/ping"]
      interval: 2s
      timeout: 2s
      retries: 1000
      start_period: 10s
    environment:
      JATOS_DB_URL: 'jdbc:mysql://db/jatos?characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC'
      JATOS_DB_USERNAME: 'jatosuser'
      JATOS_DB_PASSWORD: 'abc123'
      JATOS_DB_DRIVER: 'com.mysql.cj.jdbc.Driver'
      JATOS_SECRET: 'my-secret-secret'
    command:
      # If you're running multiple JATOS instances
      #- '-Djatos.multiNode=true'
      # Get JATOS' logs to the stdout, e.g. for debugging
      #- '-Djatos.logs.appender=ASYNCSTDOUT'
    volumes:
      - jatos-logs:/opt/jatos/logs
      - jatos-data:/opt/jatos_data
      # Configure JATOS by binding a jatos.conf
      - ./jatos.conf:/opt/jatos/conf/jatos.conf:ro

  db:
    image: mysql:8.0.32-debian
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 2s
      timeout: 2s
      retries: 30
    environment:
      MYSQL_DATABASE: 'jatos'
      MYSQL_USER: 'jatosuser'
      MYSQL_PASSWORD: 'abc123'
      MYSQL_ROOT_PASSWORD: 'abc123'
    command:
      # Deactivate MySQL's binary log (https://www.jatos.org/JATOS-with-MySQL.html)
      #- '--skip-log-bin'
    cap_add:
      # Fix "mbind: Operation not permitted" (https://stackoverflow.com/q/55559386/1278769)
      - SYS_NICE
    volumes:
      - jatos-db:/var/lib/mysql
    ports:
      - 3307:3306
      
volumes:
  jatos-data:
  jatos-logs:
  jatos-db:
